### ISSUE TITLE
Launch  BISCUT_preprocessing.py fails: issue with input

### ISSUE THREAD

**Issue by kokonech** [beroukhim-lab/BISCUT-py3#7]
Hi! I tried to run on CNV profiles from methylation data, but BISCUIT failed. Main error was the following:

```
Traceback (most recent call last):
  File "/b06x-isilon/b06x-m/mb/analysis/medullo/okonechn/BISCUT-py3-main/BISCUT_preprocessing.py", line 256, in <module>
    take_care_arms(tumor_type, date_suffix)
  File "/b06x-isilon/b06x-m/mb/analysis/medullo/okonechn/BISCUT-py3-main/BISCUT_preprocessing.py", line 251, in take_care_arms
    result.get(9999999)
  File "/b06x-isi/share/csw/15.x/x86_64_generic/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'start'
```
I only edited _tumor_type, seg_file_suffix_ and _date_suffix_. Setting _amplitude_threshold_ to 0.1 also did not help, even though distribution of Segment_mean is from -0.6 to 0.6. Here's the head of the CNV profile file collected from methylation data:
```
Sample	Chromosome	Start	End	Num_Probes	Segment_Mean
ICGC_MB305	1	521369	750000	10	0.011
ICGC_MB305	1	750001	800000	10	-0.037
ICGC_MB305	1	800001	850000	10	-0.033
ICGC_MB305	1	850001	900000	10	0.014
ICGC_MB305	1	900001	950000	10	0.008
ICGC_MB305	1	950001	1000000	10	0.044
...
```
What could be the problem? Any suggestions how to fix this?

P.S. I followed the tutorial in documentation, it went well but initailly running the  BISCUT_preprocessing.py required the input file to be located in the docs subfolder:
`FileNotFoundError: [Errno 2] No such file or directory: 'docs/PANCAN_ISAR.seg.txt'`

I found this is hard-coded there. Probably could be noted in documentation.

**Comment by sanroman-24** [comment]
Hi kokonech, I had come across the same issue. In my case the cryptic error was caused by the inclusion of "X" as one of the chromosomes. This messes up completely the filtering that BISCUT_preprocessing.py seems to be doing. I hope this helps!
